name: Rocket

schedules:
- cron: "0 4 * * *"
  displayName: Nightly 4AM UTC Build
  branches:
    include:
    - master
    - v0.4
  always: true

jobs:
- template: azure-pipelines-template.yml
  parameters:
    name: macOS
    vmImage: macOS-10.14

- template: azure-pipelines-template.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04

- template: azure-pipelines-template.yml
  parameters:
    name: Windows
    vmImage: windows-2019
